### ISSUE TITLE
Improve figures for color-blind people

### ISSUE THREAD

**Issue by haesleinhuepf** [NeuBIAS/neubias-springer-book-2020#2]
Hi Kota @miura ,

it's so good to have this repository so that we can discuss and potentially improve the book. Great initiative! Thanks!
However, I would like to support you and improve the figures for colour-blind people. However, the figures are not part of the repository...
I would expect image files [here](https://github.com/NeuBIAS/neubias-springer-book-2020/tree/master/Ch2%20Measurements%20of%20Intensity%20Dynamics%20at%20the%20Periphery%20of%20the%20Nucleus/Images) corresponding to figure 2.1:
![image](https://user-images.githubusercontent.com/12660498/67946352-7b846b80-fbe1-11e9-95db-8ec766bc2520.png) and [here](https://github.com/NeuBIAS/neubias-springer-book-2020/tree/master/Ch3%203D%20Quantitative%20Colocalisation%20Analysis/Images) for figure 3.1.

Figures 3.5, 3.6 and 3.7 might also want to be piped through the "Replace Red with Magenta" plugin in Fiji ;-)

Before: 
![image](https://user-images.githubusercontent.com/12660498/67946723-3c0a4f00-fbe2-11e9-8b49-45d5ed44f6ff.png)

After:
![image](https://user-images.githubusercontent.com/12660498/67946743-44628a00-fbe2-11e9-8ad1-e13e7ed7d3ba.png)

Let me know how I can help.

Cheers.
Robert

**Comment by norsimon** [comment]
Hi Robert,

Very good points. Thank you!
Kota can comment more, here is my current take:

- The repository was, at least initially, only meant for code and images that are processed as part of following the workflows in the chapters. That is, no figures from the book as such, just supplementary information.
- Yes, correcting all images to avoid red-green or other dichromacy issues really is something we should have done (using Fiji's features for this). Not sure how much we can change the book now, but I believe it is worth asking Springer (ball pass --> Kota/Natasa).

Thanks,
Simon

**Comment by miura** [comment]
Great suggestion @haesleinhuepf ! I will work on it. This is the "Image data ethics", as it concerns with science in terms of the social value.

**Comment by fabricecordelieres** [comment]
Hi,

Not sure this was the way you wanted it to be organized, but I've created a folder in the coloc chapter named "Figures_Dischromacy_Corrected". It contains an alternative version of all the color figures which should be complient to the "image data ethics" policy ;-)

**Comment by miura** [comment]
I now added replacements for sample image data and figures. Thanks to @haesleinhuepf ! and also to @fabricecordelieres and @norsimon for quick actions.

**Comment by haesleinhuepf** [comment]
Thanks everyone! 💙💚♥️
